"""
create_train_notebook.py
Run once locally:  python colab/create_train_notebook.py
Generates:        colab/comic_studio_train.ipynb

GPU needed: A100 80GB (Colab Pro+). Do NOT use T4 — will OOM on FLUX.
Runtime:    90-150 min for 1300 images at 2500 steps with DoRA rank 16.
"""
import json
from pathlib import Path

def cell(source: list[str]) -> dict:
    return {"cell_type": "code", "metadata": {}, "source": source,
            "execution_count": None, "outputs": []}

def md(source: list[str]) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


cells = [
    md([
        "# 🎨 Comic Studio — FLUX Style LoRA Training\n\n",
        "Trains a FLUX.1-dev style LoRA with **DoRA** (Weight-Decomposed LoRA).\n\n",
        "| Setting | Value | Why |\n",
        "|---|---|---|\n",
        "| Rank | 16 | Sweet spot for FLUX style — higher risks absorbing anatomy |\n",
        "| DoRA | ✅ | Separates direction from magnitude → cleaner style isolation |\n",
        "| Steps | 2500 | ~7.7 passes through 1300 images at eff. batch 4 |\n",
        "| Caption dropout | 10% | Trigger is additive, not always-present |\n",
        "| EMA decay | 0.9999 | Averages last ~1000 steps → very smooth final weights |\n",
        "| LR scheduler | constant + warmup | Stable, easy to read loss curves |\n\n",
        "## GPU required\n",
        "**A100 80GB** — Colab Pro+. Switch runtime before starting.\n\n",
        "## Order\n",
        "Run **A1 → A2 → B1 → C1 → C2** — C2 is the long one (~90-150 min).",
    ]),
    md(["---\n# ━━ SECTION A — Setup ━━"]),
    cell([
        "# A1 — Mount Drive & configure training\n",
        "from google.colab import drive\n",
        "drive.mount('/content/drive')\n",
        "import os, torch\n",
        "\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "HF_TOKEN      = 'paste_your_hf_token_here'\n",
        "TRIGGER_WORD  = 'comicstyle'\n",
        "OUTPUT_NAME   = 'comicstyle_flux_v1'\n",
        "LORA_RANK     = 16        # rank 16 = FLUX style sweet spot\n",
        "USE_DORA      = True      # DoRA: cleaner trigger on/off separation\n",
        "TRAIN_STEPS   = 2500      # ~7.7 passes through 1300 images\n",
        "LEARNING_RATE = '1e-4'\n",
        "WARMUP_STEPS  = 100\n",
        "RESOLUTION    = 1024\n",
        "SAVE_EVERY    = 500\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "DRIVE_ROOT   = '/content/drive/MyDrive/ComicStudio'\n",
        "TRAIN_IMAGES = f'{DRIVE_ROOT}/training_images'\n",
        "OUTPUT_DIR   = f'{DRIVE_ROOT}/loras'\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "\n",
        "os.environ['HF_TOKEN'] = HF_TOKEN\n",
        "os.environ['HUGGING_FACE_HUB_TOKEN'] = HF_TOKEN\n",
        "\n",
        "# Verify GPU\n",
        "gpu  = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'\n",
        "vram = torch.cuda.get_device_properties(0).total_memory / 1024**3 if torch.cuda.is_available() else 0\n",
        "if vram < 70:\n",
        "    print(f'WARNING: Only {vram:.0f}GB VRAM ({gpu}). FLUX+DoRA needs A100 80GB.')\n",
        "else:\n",
        "    print(f'GPU OK: {gpu} ({vram:.0f}GB)')\n",
        "\n",
        "# Verify dataset\n",
        "imgs = [f for f in os.listdir(TRAIN_IMAGES) if f.lower().endswith(('.png','.jpg','.jpeg','.webp'))]\n",
        "caps = [f for f in os.listdir(TRAIN_IMAGES) if f.endswith('.txt')]\n",
        "uncapped = len(imgs) - len(caps)\n",
        "if uncapped > 0:\n",
        "    print(f'WARNING: {uncapped} images have no caption. Run caption notebook first!')\n",
        "else:\n",
        "    print(f'Dataset OK: {len(imgs)} images, all captioned')\n",
        "\n",
        "print(f'Trigger   : {TRIGGER_WORD}')\n",
        "print(f'Rank      : {LORA_RANK}  |  DoRA: {USE_DORA}')\n",
        "print(f'Steps     : {TRAIN_STEPS}  |  LR: {LEARNING_RATE}  |  Warmup: {WARMUP_STEPS}')\n",
        "print(f'Output    : {OUTPUT_DIR}/{OUTPUT_NAME}.safetensors')",
    ]),
    cell([
        "# A2 — Verify 5 random captions before training\n",
        "import os, random\n",
        "\n",
        "txts = [f for f in os.listdir(TRAIN_IMAGES) if f.endswith('.txt')]\n",
        "for f in random.sample(txts, min(5, len(txts))):\n",
        "    cap = open(os.path.join(TRAIN_IMAGES, f)).read().strip()\n",
        "    ok  = 'OK' if cap.startswith(TRIGGER_WORD) else 'MISSING TRIGGER'\n",
        "    print(f'[{ok}] {f}')\n",
        "    print(f'      {cap[:100]}')\n",
        "    print()",
    ]),
    md(["---\n# ━━ SECTION B — Install ai-toolkit (once per session) ━━"]),
    cell([
        "# B1 — Clone ai-toolkit & install requirements (~3-5 min)\n",
        "import os\n",
        "\n",
        "if not os.path.exists('/content/ai-toolkit'):\n",
        "    !git clone https://github.com/ostris/ai-toolkit /content/ai-toolkit\n",
        "else:\n",
        "    !git -C /content/ai-toolkit pull --quiet\n",
        "    print('ai-toolkit already installed, pulled latest')\n",
        "\n",
        "!pip install -q -r /content/ai-toolkit/requirements.txt\n",
        "print('B1 done — ai-toolkit ready')",
    ]),
    md(["---\n# ━━ SECTION C — Train ━━"]),
    cell([
        "# C1 — Build training config\n",
        "import yaml, os\n",
        "\n",
        "config = {\n",
        "    'job': 'extension',\n",
        "    'config': {\n",
        "        'name': OUTPUT_NAME,\n",
        "        'process': [{\n",
        "            'type': 'sd_trainer',\n",
        "            'training_folder': OUTPUT_DIR,\n",
        "            'device': 'cuda:0',\n",
        "            'trigger_word': TRIGGER_WORD,\n",
        "\n",
        "            'network': {\n",
        "                'type': 'lora',\n",
        "                'linear': LORA_RANK,\n",
        "                'linear_alpha': LORA_RANK,\n",
        "                # DoRA separates weight magnitude from direction.\n",
        "                # Result: cleaner trigger-on vs trigger-off separation.\n",
        "                # ~15% slower but strongly recommended for style LoRAs.\n",
        "                'network_kwargs': {'use_dora': USE_DORA},\n",
        "            },\n",
        "\n",
        "            'save': {\n",
        "                'dtype': 'float16',\n",
        "                'save_every': SAVE_EVERY,\n",
        "                'max_step_saves_to_keep': 4,\n",
        "            },\n",
        "\n",
        "            'datasets': [{\n",
        "                'folder_path': TRAIN_IMAGES,\n",
        "                'caption_ext': 'txt',\n",
        "                # 10% dropout: forces model to learn style unconditionally.\n",
        "                # Without this, style may appear even without the trigger word.\n",
        "                'caption_dropout_rate': 0.1,\n",
        "                'shuffle_tokens': False,\n",
        "                'cache_latents_to_disk': True,\n",
        "                'resolution': [RESOLUTION],\n",
        "                'center_crop': False,\n",
        "                # Keep False: preserves left/right consistency in comic panels\n",
        "                'random_flip': False,\n",
        "            }],\n",
        "\n",
        "            'train': {\n",
        "                'batch_size': 1,\n",
        "                'steps': TRAIN_STEPS,\n",
        "                'gradient_accumulation_steps': 4,\n",
        "                'train_unet': True,\n",
        "                # Keep T5 + CLIP frozen. Style lives in the UNet/DiT.\n",
        "                # Training T5 risks degrading your long prompt understanding.\n",
        "                'train_text_encoder': False,\n",
        "                'gradient_checkpointing': True,\n",
        "                'noise_scheduler': 'flowmatch',\n",
        "                'optimizer': 'adamw8bit',\n",
        "                'lr': LEARNING_RATE,\n",
        "                # constant_with_warmup: stable, predictable loss curves.\n",
        "                # Warmup prevents LR spikes in the first 100 steps.\n",
        "                'lr_scheduler': 'constant_with_warmup',\n",
        "                'lr_warmup_steps': WARMUP_STEPS,\n",
        "                'max_grad_norm': 1.0,\n",
        "                'ema_config': {\n",
        "                    'use_ema': True,\n",
        "                    # 0.9999 averages ~last 1000 steps at 2500 total.\n",
        "                    # 0.99 would only average last ~100 — too short for long runs.\n",
        "                    'ema_decay': 0.9999,\n",
        "                },\n",
        "                'dtype': 'bf16',\n",
        "                'skip_first_sample': True,\n",
        "            },\n",
        "\n",
        "            'model': {\n",
        "                'name_or_path': 'black-forest-labs/FLUX.1-dev',\n",
        "                'is_flux': True,\n",
        "                # 8-bit quantize base model to fit DoRA rank-16 in A100 80GB\n",
        "                'quantize': True,\n",
        "            },\n",
        "\n",
        "            'sample': {\n",
        "                'sampler': 'flowmatch',\n",
        "                'sample_every': SAVE_EVERY,\n",
        "                'width': 1024, 'height': 1024,\n",
        "                'prompts': [\n",
        "                    # WITH trigger — these should look like your comic style\n",
        "                    f'{TRIGGER_WORD}, young woman standing in a city street, looking at camera',\n",
        "                    f'{TRIGGER_WORD}, bearded man in a jacket, dramatic lighting',\n",
        "                    f'{TRIGGER_WORD}, urban rooftop at night, neon lights',\n",
        "                    f'{TRIGGER_WORD}, close-up portrait of a woman with curly hair',\n",
        "                    # WITHOUT trigger — should look like base FLUX (sanity check)\n",
        "                    'young woman standing in a city street, looking at camera',\n",
        "                ],\n",
        "                'neg': '',\n",
        "                'seed': 42,\n",
        "                'walk_seed': True,\n",
        "                'guidance_scale': 4.5,\n",
        "                'sample_steps': 28,\n",
        "            },\n",
        "        }]\n",
        "    },\n",
        "    'meta': {'name': OUTPUT_NAME, 'version': '1.0'},\n",
        "}\n",
        "\n",
        "config_path = f'/content/{OUTPUT_NAME}_config.yaml'\n",
        "with open(config_path, 'w') as f:\n",
        "    yaml.dump(config, f, sort_keys=False)\n",
        "\n",
        "print(f'C1 done — config written to {config_path}')\n",
        "print(f'Steps     : {TRAIN_STEPS}')\n",
        "print(f'Rank      : {LORA_RANK}  |  DoRA: {USE_DORA}')\n",
        "print(f'LR        : {LEARNING_RATE}  |  Warmup: {WARMUP_STEPS} steps')\n",
        "print(f'Caption dropout: 10%  |  EMA decay: 0.9999')\n",
        "print()\n",
        "print('Expected loss curve:')\n",
        "print('  step  500 -> ~0.08-0.10  (normal start)')\n",
        "print('  step 1500 -> ~0.05-0.06  (good progress)')\n",
        "print('  step 2500 -> ~0.03-0.05  (ideal final)')\n",
        "print('  < 0.02 at end = overfit | > 0.07 at end = add 500 more steps')",
    ]),
    cell([
        "# C2 — START TRAINING\n",
        "# Runs 90-150 min. You can close the browser tab — it keeps going.\n",
        "# Preview images saved to Drive every 500 steps (4 WITH trigger + 1 WITHOUT).\n",
        "# Compare trigger vs no-trigger previews to track style isolation quality.\n",
        "\n",
        "import subprocess, sys, os, time\n",
        "\n",
        "print('Starting training...')\n",
        "print(f'  {OUTPUT_NAME}  |  {TRAIN_STEPS} steps  |  rank {LORA_RANK}  |  DoRA={USE_DORA}')\n",
        "print('-' * 60)\n",
        "\n",
        "t0 = time.time()\n",
        "result = subprocess.run(\n",
        "    [sys.executable, 'run.py', config_path],\n",
        "    cwd='/content/ai-toolkit',\n",
        ")\n",
        "elapsed = (time.time() - t0) / 60\n",
        "\n",
        "if result.returncode == 0:\n",
        "    final = f'{OUTPUT_DIR}/{OUTPUT_NAME}/{OUTPUT_NAME}.safetensors'\n",
        "    if os.path.exists(final):\n",
        "        mb = os.path.getsize(final) / 1024 / 1024\n",
        "        print(f'Training complete in {elapsed:.1f} min')\n",
        "        print(f'LoRA saved: {final} ({mb:.0f} MB)')\n",
        "    else:\n",
        "        print(f'Training finished but LoRA not at expected path. Check {OUTPUT_DIR}/')\n",
        "else:\n",
        "    print(f'Training FAILED (exit {result.returncode}) after {elapsed:.1f} min')\n",
        "    print('Common causes:')\n",
        "    print('  OOM       -> set USE_DORA=False and retry, or reduce LORA_RANK to 8')\n",
        "    print('  HF token  -> accept FLUX.1-dev license at huggingface.co')\n",
        "    print('  No capts  -> run caption notebook first')",
    ]),
    md(["---\n# ━━ SECTION D — After Training ━━"]),
    cell([
        "# D1 — Copy final LoRA to Drive/loras/ for Comic Studio\n",
        "import os, shutil\n",
        "\n",
        "src = f'{OUTPUT_DIR}/{OUTPUT_NAME}/{OUTPUT_NAME}.safetensors'\n",
        "dst = f'{OUTPUT_DIR}/{OUTPUT_NAME}.safetensors'\n",
        "\n",
        "if os.path.exists(src):\n",
        "    shutil.copy2(src, dst)\n",
        "    mb = os.path.getsize(dst) / 1024 / 1024\n",
        "    print(f'Copied to {dst} ({mb:.0f} MB)')\n",
        "    print()\n",
        "    print('To activate in Comic Studio:')\n",
        "    print(f'  Backend notebook -> A5 cell:')\n",
        "    print(f'    STYLE_LORA_TRIGGER = \"{TRIGGER_WORD}\"')\n",
        "    print(f'    STYLE_LORA_WEIGHT  = \"1.0\"')\n",
        "    print(f'  Then re-run A5 and A6 to restart server.')\n",
        "else:\n",
        "    print(f'File not found: {src}')\n",
        "    print('Searching for .safetensors in output dir...')\n",
        "    for root, dirs, files in os.walk(OUTPUT_DIR):\n",
        "        for f in files:\n",
        "            if f.endswith('.safetensors'):\n",
        "                p = os.path.join(root, f)\n",
        "                print(f'  Found: {p} ({os.path.getsize(p)/1024/1024:.0f} MB)')",
    ]),
    cell([
        "# D2 — Quick quality test: trigger on vs off side-by-side\n",
        "# Generates 4 pairs: WITH trigger (should look like your style)\n",
        "#                    WITHOUT trigger (should look like base FLUX)\n",
        "import torch\n",
        "from diffusers import FluxPipeline\n",
        "from IPython.display import display, Image as IPImage\n",
        "import io\n",
        "\n",
        "LORA_PATH = f'{OUTPUT_DIR}/{OUTPUT_NAME}.safetensors'\n",
        "\n",
        "print('Loading FLUX + LoRA for quality test...')\n",
        "pipe = FluxPipeline.from_pretrained(\n",
        "    'black-forest-labs/FLUX.1-dev',\n",
        "    torch_dtype=torch.bfloat16, token=HF_TOKEN,\n",
        ").to('cuda')\n",
        "pipe.load_lora_weights(LORA_PATH)\n",
        "\n",
        "test_pairs = [\n",
        "    'young woman standing in a city street, looking at camera',\n",
        "    'bearded man in a leather jacket, urban background',\n",
        "    'rooftop cityscape at night, neon lights',\n",
        "]\n",
        "\n",
        "for prompt in test_pairs:\n",
        "    for weight, label in [(1.0, 'WITH trigger'), (0.0, 'base FLUX')]:\n",
        "        pipe.set_adapters(['default'], adapter_weights=[weight])\n",
        "        full_prompt = f'{TRIGGER_WORD}, {prompt}' if weight > 0 else prompt\n",
        "        print(f'[{label}]: {full_prompt}')\n",
        "        img = pipe(\n",
        "            full_prompt, num_inference_steps=28,\n",
        "            guidance_scale=4.5, height=1024, width=1024,\n",
        "            generator=torch.Generator().manual_seed(42),\n",
        "        ).images[0]\n",
        "        buf = io.BytesIO(); img.save(buf, 'PNG'); buf.seek(0)\n",
        "        display(IPImage(data=buf.read(), width=400))\n",
        "\n",
        "print('Pairs should look different. If identical -> LoRA too weak.')\n",
        "print('If no-trigger also has your style -> caption dropout was too low.')",
    ]),
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "name": "Comic Studio — FLUX LoRA Training",
            "provenance": [],
            "gpuType": "A100",
        },
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "accelerator": "GPU",
    },
    "cells": cells,
}

out = Path(__file__).parent / "comic_studio_train.ipynb"
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"[OK] Created: {out}")
print("Settings baked in:")
print("  Rank 16  |  DoRA  |  2500 steps  |  LR 1e-4")
print("  constant_with_warmup (100 warmup)  |  EMA 0.9999")
print("  caption dropout 10%  |  random_flip=False")
